[General]
network = flora.simulations.LoRaNetworkTest
output-vector-file = ../results/DER_2GW-s-10ed${runnumber}.ini.vec
output-scalar-file = ../results/DER_2GW-s-10ed${runnumber}.ini.sca
**.maxTransmissionDuration = 1600000s
**.vector-recording = true
**.scalar-recording = true
**.EV_INFO = true
*.networkServerApp.EV_INFO = true

*.debug = true
**.verbosity = 4

rng-class = "cMersenneTwister"
**.loRaGW[*].numUdpApps = 1
**.loRaGW[*].packetForwarder.localPort = 2000
**.loRaGW[*].packetForwarder.destPort = 1000 
**.loRaGW[*].packetForwarder.destAddresses = "networkServer"
**.loRaGW[*].packetForwarder.indexNumber = 0

**.networkServer.numApps = 1
**.networkServer.**.evaluateADRinServer = true
**.networkServer.app[0].typename = "NetworkServerApp"
**.networkServer.app[0].destAddresses = "loRaGW[*]"
**.networkServer.app[0].destPort = 2000
**.networkServer.app[0].localPort = 1000

**.numberOfPacketsToSend = 5000 #${numberOfPAckets = 200..5000 step 200} #100 #obviously 0 means infinite number of packets
**.timeToFirstPacket = exponential(10s)
**.timeToNextPacket = exponential(250s)  # or fixed 250
sim-time-limit = 2500000s              # gives some buffer

*.networkServer.app[0].preambleSymbols = 8
*.networkServer.app[0].defaultPayloadSize = 20

simtime-resolution = -11
**.repeat = 5

**.alohaChannelModel = false

#nodes features
**.loRaNodes[*].**.initFromDisplayString = false
**.loRaNodes[*].**.evaluateADRinNode = true
**.loRaNodes[*].**initialLoRaBW = 125 kHz
**.loRaNodes[*].**initialLoRaCR = 4
**.loRaNodes[*].numApps = 1
**.loRaNodes[*].app[0].typename = "SimpleLoRaApp"

#gateway features
**.LoRaGWNic.radio.iAmGateway = true
**.loRaGW[*].**.initFromDisplayString = false

#power consumption features
**.loRaNodes[*].LoRaNic.radio.energyConsumer.typename = "LoRaEnergyConsumer"
**.loRaNodes[*].**.energySourceModule = "^.IdealEpEnergyStorage"
**.loRaNodes[*].LoRaNic.radio.energyConsumer.configFile = xmldoc("../energyConsumptionParameters.xml")

#general features
**.sigma = 3.57
**.constraintAreaMinX = 0m
**.constraintAreaMinY = 0m
**.constraintAreaMinZ = 0m
**.constraintAreaMaxZ = 0m

LoRaNetworkTest.**.radio.separateTransmissionParts = false
LoRaNetworkTest.**.radio.separateReceptionParts = false

**.ipv4Delayer.config = xmldoc("../cloudDelays.xml")
**.radio.radioMediumModule = "LoRaMedium"
**.minInterferenceTime = 0s
**.displayAddresses = false

# **.numberOfGateways = 8
**.constraintAreaMaxX = 5000.0m
**.constraintAreaMaxY = 5000.0m

**.numberOfGateways = 2
**.numberOfNodes = 10
**.simulationTimeLimit = 1600000s # Simulate for 1 hour

**.networkServer.app[0].adrMethod = ${"ADRopt"}
**.LoRaMedium.pathLossType = "LoRaLogNormalShadowing"
**.energyDetection = -110dBm

**.loRaNodes[*].radio.vector-recording = true

**.loRaNodes[*].LoRaNic.spreadingFactor = 12#uniform(7,12)

**.loRaNodes[*].LoRaNic.frequency = 868.1MHz, 868.3MHz, 868.5MHz
**.loRaNodes[*].LoRaNic.bandwidth = 125kHz
**.loRaNodes[*].LoRaNic.packetInterval = 144s  # 2.4 minutes

# LoRa Gateways (Modify X, Y based on paper positions or random placement)
**.loRaGW[0].mobility.initialX = 150m
**.loRaGW[0].mobility.initialY = 150m

**.loRaGW[1].mobility.initialX = 650m
**.loRaGW[1].mobility.initialY = 350m

# LoRa End Node Position
**.loRaNodes[0].**.initialX = 590.63m
**.loRaNodes[0].**.initialY = 529.08m
**.loRaNodes[1].**.initialX = 488.29m
**.loRaNodes[1].**.initialY = 504.24m
**.loRaNodes[2].**.initialX = 561.60m
**.loRaNodes[2].**.initialY = 570.25m
**.loRaNodes[3].**.initialX = 556.86m
**.loRaNodes[3].**.initialY = 529.63m
**.loRaNodes[4].**.initialX = 527.85m
**.loRaNodes[4].**.initialY = 484.11m
**.loRaNodes[5].**.initialX = 555.27m
**.loRaNodes[5].**.initialY = 541.84m
**.loRaNodes[6].**.initialX = 561.11m
**.loRaNodes[6].**.initialY = 614.96m
**.loRaNodes[7].**.initialX = 557.86m
**.loRaNodes[7].**.initialY = 575.17m
**.loRaNodes[8].**.initialX = 500.41m
**.loRaNodes[8].**.initialY = 537.16m
**.loRaNodes[9].**.initialX = 530.53m
**.loRaNodes[9].**.initialY = 594.82m